# Generated by Django 6.0.2 on 2026-03-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Иконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='halls/', verbose_name='Фото зала')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Зал / Атмосфера',
                'verbose_name_plural': 'Залы / Атмосфера',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+996 555 123 456', max_length=50, verbose_name='Телефон (текст)')),
                ('phone_link', models.CharField(default='996555123456', max_length=50, verbose_name='Телефон (для ссылки tel:)')),
                ('whatsapp', models.CharField(default='996555123456', max_length=50, verbose_name='WhatsApp (только цифры)')),
                ('address', models.CharField(default='г. Бишкек, ул. Манаса, 12', max_length=200, verbose_name='Адрес')),
                ('hours', models.CharField(default='Ежедневно: 10:00 — 00:00', max_length=100, verbose_name='Режим работы')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('about_text', models.TextField(default='Мы не просто готовим еду. Мы воссоздаем историю.', verbose_name='Текст «Философия Казыны»')),
                ('map_embed', models.TextField(blank=True, help_text='Вставьте только src из кода встраивания Google Maps', verbose_name='Ссылка Google Maps (src для iframe)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('btn_text', models.CharField(default='Смотреть меню', max_length=50, verbose_name='Текст кнопки')),
                ('btn_link', models.CharField(default='#menu', max_length=100, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Фото слайда')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Слайд баннера',
                'verbose_name_plural': 'Слайды баннера',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (сом)')),
                ('image', models.ImageField(upload_to='menu/', verbose_name='Фото')),
                ('tag', models.CharField(blank=True, choices=[('', '—'), ('top', 'ТОП ВКУС'), ('new', 'НОВИНКА'), ('fire', 'НА ОГНЕ'), ('tea', 'К ЧАЮ'), ('fresh', 'СВЕЖЕЕ'), ('special', 'ОСОБОЕ')], max_length=20, verbose_name='Бейдж')),
                ('is_week_special', models.BooleanField(default=False, verbose_name='Блюдо недели?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['order'],
            },
        ),
    ]
