# Generated by Django 6.0.2 on 2026-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='row',
            field=models.CharField(choices=[('top', 'Верхняя строка'), ('bottom', 'Нижняя строка')], default='top', max_length=10, verbose_name='Строка галереи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Фото секции «Философия» (левый блок)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Фоновое фото (Hero-секция)'),
        ),
    ]
