# Generated by Django 6.0.2 on 2026-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_galleryimage_row_sitesettings_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Широкоформатное фото для фона секции. Если не задано — используется фото карточки.', null=True, upload_to='halls/bg/', verbose_name='Фото фона (при наведении)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(upload_to='halls/', verbose_name='Фото зала (карточка)'),
        ),
    ]
